{% set name = "edgar-sec" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/{{ name }}/edgar_sec-{{ version }}.tar.gz
  sha256: 8ff418237992aec18c6c113e0b3c1248cf2cf7fe17a5558a468f139205115604

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - httpx
    - tenacity
    - cachetools
    - asyncache

test:
  imports:
    - edgar_sec
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/nikhilxsunder/edgar-sec
  doc_url: https://nikhilxsunder.github.io/edgar-sec/
  dev_url: https://github.com/nikhilxsunder/edgar-sec
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  summary: A feature-rich Python package for interacting with the US Securities and Exchange Commission API (EDGAR)
  description: |
    edgar-sec is a Python package for interacting with the US Securities and Exchange Commission EDGAR API.
    It provides a feature-rich interface with:
    - Native support for asynchronous requests (async)
    - All method outputs are mapped to dataclasses for better usability
    - Local caching for easier data access and faster execution times
    - Built-in rate limiter that doesn't exceed 10 calls per second
    - MyPy compatible type stubs

extra:
  recipe-maintainers:
    - nikhilxsunder
